-- Scripts para criado do projeto --
CREATE TABLE USUARIO (
	EMAIL VARCHAR(100) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
 	PRIMARY KEY (EMAIL) 
);
CREATE TABLE VEICULOS (
	ID INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
  	MARCA VARCHAR(100) NOT NULL,
  	TIPO VARCHAR(100) NOT NULL,
  	NOME_PECAS VARCHAR(100) NOT NULL,
  	PRIMARY KEY (ID) 
);

CREATE TABLE PECAS (
	NOME VARCHAR(100) NOT NULL,
  	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (NOME) 
);

ALTER TABLE VEICULOS
ADD FOREIGN KEY (NOME_PECAS) 
REFERENCES PECAS(NOME);

CREATE SEQUENCE S_VEICULOS 
	MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 ;
    