-- Scripts criado para o projeto --
CREATE TABLE USUARIO (
	EMAIL VARCHAR(100) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
 	PRIMARY KEY (EMAIL) 
);
CREATE TABLE VEICULOS (
	NOME VARCHAR(100) NOT NULL,
  	MARCA VARCHAR(100) NOT NULL,
  	TIPO VARCHAR(100) NOT NULL,
  	PRIMARY KEY (NOME) 
);

CREATE TABLE PECAS (
	NOME VARCHAR(100) NOT NULL,
  	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (NOME) 
);

ALTER TABLE PECAS
ADD FOREIGN KEY (NOME_VEICULO) 
REFERENCES VEICULOS(NOME);